compilers:
  - compiler:
      environment: {}
      extra_rpaths: []
      modules: []
      operating_system: rhel9
      paths:
        cc: /usr/bin/gcc
        cxx: /usr/bin/g++
        f77: /usr/bin/gfortran
        fc: /usr/bin/gfortran
      spec: gcc@=11.5.0.rhel9 languages=c,c++,fortran
      target: x86_64
  - compiler:
      environment: {}
      extra_rpaths: []
      flags:
        cppflags: -fpic
      modules: []
      operating_system: rhel9
      paths:
        cc: /scratch/spack/dist/apps/linux-rhel9-x86_64_v4/gcc-11.5.0.rhel9/gcc-13.3.0-hnh5a2xnrrh622j6ii6bke2vqatpj7pf/bin/gcc
        cxx: /scratch/spack/dist/apps/linux-rhel9-x86_64_v4/gcc-11.5.0.rhel9/gcc-13.3.0-hnh5a2xnrrh622j6ii6bke2vqatpj7pf/bin/g++
        f77: /scratch/spack/dist/apps/linux-rhel9-x86_64_v4/gcc-11.5.0.rhel9/gcc-13.3.0-hnh5a2xnrrh622j6ii6bke2vqatpj7pf/bin/gfortran
        fc: /scratch/spack/dist/apps/linux-rhel9-x86_64_v4/gcc-11.5.0.rhel9/gcc-13.3.0-hnh5a2xnrrh622j6ii6bke2vqatpj7pf/bin/gfortran
      spec: gcc@=13.3.0 languages=c,c++,fortran
      target: x86_64
