concretizer:
  duplicates:
    strategy: minimal
  error_on_timeout: true
  os_compatible: {}
  reuse: true
  splice:
    automatic: true
    explicit: []
  targets:
    granularity: microarchitectures
    host_compatible: true
  timeout: 0
  unify: when_possible
